### ISSUE TITLE
Adwaita theme v2?

### ISSUE THREAD

**Issue by aaronliu0130** [odiegoduarte/ventoy-themes#1]
These themes look wonderful! However, the Adwaita theme doesn't have any 1920x1080 versions. Could you export one? Thanks!

**Comment by wombatus2137** [comment]
Could you do the same for Ocean Blue and Adwaita Blue? @odiegoduarte

**Comment by odiegoduarte** [comment]
Updated themes  @aaronliu0130 @wombatus2137 

**Ventoy Adwaita Theme**
[Ventoy Adwaita Theme - pling.com](https://www.pling.com/p/2083481/)
[Ventoy Adwaita Theme V2 - GitHub](https://github.com/odiegoduarte/ventoy-themes/releases/tag/0.8)

**Ventoy Adwaita Blue Theme**
[Ventoy Adwaita Blue Theme - pling.com](https://www.pling.com/p/2093957/)
[Ventoy Adwaita Blue Theme V2 Update  - GitHub](https://github.com/odiegoduarte/ventoy-themes/releases/tag/0.9)
